# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_user', '0002_twitteruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='name',
            field=models.CharField(default='no name', max_length=200),
        ),
    ]
